using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;

namespace DTBK.Engine.Estimation;

public enum GuiValueKind { Input, Derived, Lookup, Formula, Reference, DisplayOnly }
public enum GuiControlKind { TextBox, NumericBox, ComboBox, CheckBox, DatePicker, Button, DataGrid, SubTable, FormulaBar, FilterBox, Tree, VerticalScrollBar, HorizontalScrollBar, Tab, Splitter, StatusBar }
public sealed record GuiCellBinding(string SheetId, string TableId, string ColumnId, string DomainPath, GuiValueKind ValueKind, string Source, string Formula, IReadOnlyList<string> Dependencies, string InvalidationScope, GuiControlKind ControlKind = GuiControlKind.DataGrid, bool Editable = false);
public sealed record GuiTableBinding(string SheetId, string TableId, string Purpose, string RowKey, IReadOnlyList<string> Columns, string PrimarySource, IReadOnlyList<string> SubTables, IReadOnlyList<string> Commands, string RecalculationScope);
public sealed record GuiControlBinding(string ControlId, string SheetId, GuiControlKind Kind, string Region, string Workflow, string Command, string DataSource, string Output, bool Required, bool Implemented);
public sealed class GuiDataSourceContract
{
 public IReadOnlyList<GuiTableBinding> Tables { get; } public IReadOnlyList<GuiCellBinding> Cells { get; } public IReadOnlyList<GuiControlBinding> Controls { get; }
 public GuiDataSourceContract(IEnumerable<GuiTableBinding> tables,IEnumerable<GuiCellBinding> cells,IEnumerable<GuiControlBinding> controls){Tables=new ReadOnlyCollection<GuiTableBinding>(tables.ToList());Cells=new ReadOnlyCollection<GuiCellBinding>(cells.ToList());Controls=new ReadOnlyCollection<GuiControlBinding>(controls.ToList());}
 public GuiCellBinding ResolveCell(string s,string t,string c)=>Cells.Single(x=>x.SheetId==s&&x.TableId==t&&x.ColumnId==c); public IEnumerable<GuiCellBinding> ForSheet(string s)=>Cells.Where(x=>x.SheetId==s); public IEnumerable<GuiControlBinding> RequiredMissingControls()=>Controls.Where(x=>x.Required&&!x.Implemented);
}
public static class GuiDataSourceContractV1
{
 public static GuiDataSourceContract Create(){var t=new List<GuiTableBinding>();var c=new List<GuiCellBinding>();var u=new List<GuiControlBinding>();
  AddSheet(t,c,"S01","Bìa","tblCover","Project cover and document index","ProjectId",new[]{"ProjectCode","ProjectName","Category","Location","Investor","PreparedBy","LegalBasis","Revision"},"ProjectContext",Array.Empty<string>(),new[]{"EditProject","SaveProject","OpenProject"});
  AddSheet(t,c,"S02","Thuyết minh","tblBasis","Legal, norm, price and method basis","BasisId",new[]{"BasisCode","Description","EffectiveDate","Source","Selected"},"LegalBasis/NormContext/PriceContext",new[]{"tblNormSource","tblPriceSource"},new[]{"AddBasis","SelectBasis","OpenSource"});
  AddSheet(t,c,"S03","Tổng hợp","tblSummary","Canonical cost summary","SummaryId",new[]{"CostCode","Description","Amount","Percent","SourceState"},"CalculationState.Summary",new[]{"tblCostLayers","tblSummaryAudit"},new[]{"Recalculate","Explain","Export"});
  AddSheet(t,c,"S04","TH xây dựng","tblConstructionCost","Construction cost layers","CostLayerId",new[]{"DirectCost","IndirectCost","PreTaxIncome","VAT","Total"},"CalculationState.Summary",new[]{"tblDirectCost","tblIndirectCost","tblTax"},new[]{"Recalculate","Explain"});
  AddSheet(t,c,"S05","Dự toán","tblEstimateLines","BOQ and quantity estimate","WorkItemId",new[]{"No","NormCode","WorkName","Unit","Quantity","MaterialUnitPrice","LaborUnitPrice","MachineUnitPrice","TransportUnitPrice","UnitPrice","Amount","GroupId"},"ProjectItem/CalculationState.Lines",new[]{"tblNormLookup","tblLineResources","tblFormulaTrace"},new[]{"AddWork","DeleteWork","SelectNorm","EditQuantity","Calculate","Undo","Redo","Filter","ShowFormula"});
  AddSheet(t,c,"S06","Phân tích","tblAnalysis","Norm and unit-price analysis","AnalysisId",new[]{"WorkItemId","ResourceCode","ResourceType","Coefficient","Price","Amount","Formula"},"CalculationState.Resources/Trace",new[]{"tblMaterial","tblLabor","tblMachine","tblTransport"},new[]{"AnalyzeNorm","ExplainFormula","Refresh"});
  AddSheet(t,c,"S07","Vật tư","tblResources","Material/labor/machine/transport price workspace","ResourceCode",new[]{"Code","Name","Type","Unit","Coefficient","BasePrice","AdjustedPrice","Province","EffectiveDate","Source"},"ResourcePriceProvider/LaborPriceProvider/MachinePriceProvider/TransportProvider",new[]{"tblMaterialPrice","tblLaborPrice","tblMachinePrice","tblTransportRate","tblFuelPrice"},new[]{"SearchResource","SelectPrice","EditAdjustment","ImportPrice","Recalculate"});
  AddSheet(t,c,"S08","Kiểm tra","tblValidation","Validation and audit findings","FindingId",new[]{"Severity","Rule","Sheet","Table","Cell","Message","Source","Status"},"ValidationState/AuditTrace",new[]{"tblFormulaAudit","tblSourceAudit","tblDifference"},new[]{"Validate","Explain","GoToCell","Resolve"});
  AddSheet(t,c,"S09","Thẩm tra","tblReview","Review, discrepancy and approval","ReviewId",new[]{"Item","Original","Reviewed","Difference","Reason","Recommendation","Status"},"ReviewState/CalculationState",new[]{"tblReviewDetails","tblApproval"},new[]{"Compare","Accept","Reject","LockRevision"});
  AddSheet(t,c,"S10","Dự thầu","tblTender","Tender price and bid adjustment","TenderLineId",new[]{"WorkItemId","BaseAmount","Adjustment","BidUnitPrice","BidAmount","Note"},"TenderState/CalculationState",new[]{"tblBidAdjustments","tblBidSummary"},new[]{"CreateTender","AdjustPrice","CheckTender","LockTender"});
  AddSheet(t,c,"S11","Phát sinh","tblVariations","Variation and changed quantities/prices","VariationId",new[]{"ContractItem","OriginalQuantity","VariationQuantity","UnitPrice","VariationAmount","Reason","ApprovalStatus"},"VariationState/ProjectLifecycleState",new[]{"tblVariationDetail","tblVariationApproval"},new[]{"AddVariation","CalculateVariation","ApproveVariation","RejectVariation"});
  AddSheet(t,c,"S12","Thanh toán","tblPayments","Payment periods and cumulative values","PaymentId",new[]{"Period","AcceptedQuantity","AcceptedAmount","PreviousCumulative","CurrentPeriod","Cumulative","Retention","Payable","Status"},"PaymentState/ProjectLifecycleState",new[]{"tblAcceptance","tblPaymentDetail","tblCumulative"},new[]{"CreatePeriod","CalculatePayment","ApprovePayment","LockPeriod"});
  AddSheet(t,c,"S13","Quyết toán","tblFinalAccount","Contract/final-account reconciliation","SettlementId",new[]{"ContractValue","Variations","Payments","Advance","Retention","FinalValue","Difference","Status"},"FinalAccountState/ProjectLifecycleState",new[]{"tblContractReconcile","tblVariationReconcile","tblPaymentReconcile"},new[]{"Reconcile","CalculateSettlement","LockSettlement","Export"});
  AddSheet(t,c,"S14","Tiến độ","tblProgress","Schedule, quantity and value progress","ProgressId",new[]{"Period","PlannedQuantity","ActualQuantity","PlannedValue","ActualValue","ProgressPercent","Status"},"ProgressState/ProjectLifecycleState",new[]{"tblPlan","tblActual","tblProgressSummary"},new[]{"AddPeriod","CalculateProgress","ComparePlan","Export"});
  AddSheet(t,c,"S15","Báo cáo","tblReports","Canonical report projection","ReportId",new[]{"ReportType","Revision","StateVersion","SourceHash","GeneratedAt","Format","Status"},"CalculationState/ReportProjection",new[]{"tblPreview","tblExportQueue","tblReportAudit"},new[]{"Preview","Print","ExportExcel","ExportWord","ExportPdf","Package"});
  var p=new(string Column,string Path,GuiValueKind Kind,string Source,string Formula,string[] Dependencies,string Scope,GuiControlKind Control,bool Editable)[]{("No","ProjectItem.Sequence",GuiValueKind.Input,"ProjectItem","",Array.Empty<string>(),"Line",GuiControlKind.NumericBox,true),("NormCode","ProjectItem.NormCode",GuiValueKind.Lookup,"NormProvider","",new[]{"ProjectItem.NormCode"},"Line+NormAnalysis",GuiControlKind.ComboBox,true),("WorkName","CalculationState.Lines[].WorkName",GuiValueKind.Reference,"NormProvider","[Norm.Name]",new[]{"NormCode"},"Line",GuiControlKind.DataGrid,false),("Unit","CalculationState.Lines[].Unit",GuiValueKind.Reference,"NormProvider","[Norm.Unit]",new[]{"NormCode"},"Line",GuiControlKind.DataGrid,false),("Quantity","ProjectItem.Quantity",GuiValueKind.Input,"Takeoff/ManualInput","",new[]{"ProjectItem.Quantity"},"Line+Resources+Summary+Reports",GuiControlKind.NumericBox,true),("MaterialUnitPrice","CalculationState.Lines[].MaterialUnitPrice",GuiValueKind.Lookup,"ResourcePriceProvider","SPVALUE(MaterialPrice)",new[]{"NormCode","Quantity","Province","EffectiveDate"},"Line+Material+Summary",GuiControlKind.NumericBox,false),("LaborUnitPrice","CalculationState.Lines[].LaborUnitPrice",GuiValueKind.Lookup,"LaborPriceProvider","SPVALUE(LaborPrice)",new[]{"NormCode","Province","EffectiveDate"},"Line+Labor+Summary",GuiControlKind.NumericBox,false),("MachineUnitPrice","CalculationState.Lines[].MachineUnitPrice",GuiValueKind.Lookup,"MachinePriceProvider","SPVALUE(MachinePrice)",new[]{"NormCode","Province","EffectiveDate","FuelPrice"},"Line+Machine+Summary",GuiControlKind.NumericBox,false),("TransportUnitPrice","CalculationState.Lines[].TransportUnitPrice",GuiValueKind.Lookup,"TransportProvider","SPVALUE(TransportRate)*Distance",new[]{"NormCode","Distance","TransportMode","Province"},"Line+Transport+Summary",GuiControlKind.NumericBox,false),("UnitPrice","CalculationState.Lines[].UnitPrice",GuiValueKind.Formula,"CalculationState","[DirectAmount]/[Quantity]",new[]{"MaterialUnitPrice","LaborUnitPrice","MachineUnitPrice","TransportUnitPrice","Quantity"},"Line+Summary+Reports",GuiControlKind.DataGrid,false),("Amount","CalculationState.Lines[].DirectAmount",GuiValueKind.Formula,"CalculationState","PRODUCT([Quantity],[UnitPrice])",new[]{"Quantity","UnitPrice"},"Line+Summary+Reports",GuiControlKind.DataGrid,false),("GroupId","ProjectItem.GroupId",GuiValueKind.Input,"ProjectItem","",new[]{"GroupId"},"Group+Summary",GuiControlKind.ComboBox,true)};
  foreach(var x in p)c.Add(new GuiCellBinding("S05","tblEstimateLines",x.Column,x.Path,x.Kind,x.Source,x.Formula,x.Dependencies,x.Scope,x.Control,x.Editable)); AddCoreControls(u); return new GuiDataSourceContract(t,c,u);
 }
 private static void AddSheet(List<GuiTableBinding> t,List<GuiCellBinding> c,string id,string name,string table,string purpose,string rowKey,string[] cols,string source,string[] subs,string[] cmds){t.Add(new GuiTableBinding(id,table,purpose,rowKey,cols,source,subs,cmds,"DependencyGraph → affected projections → CalculationState"));foreach(var col in cols){var e=col is "Quantity" or "NormCode" or "GroupId" or "Adjustment" or "Note" or "Reason" or "Status";var k=e?GuiValueKind.Input:GuiValueKind.Reference;c.Add(new GuiCellBinding(id,table,col,$"{table}.{col}",k,source,e?"":$"[{col}]",e?new[]{$"{table}.{col}"}:Array.Empty<string>(),"Row+Table+DependentSheets",e?GuiControlKind.TextBox:GuiControlKind.DataGrid,e));}}
 private static void AddCoreControls(List<GuiControlBinding> c){c.Add(new("GUI-CMD-RECALCULATE","GLOBAL",GuiControlKind.Button,"Calculation","Calculate","CalculateEstimate","CalculationRequest → CalculationStateEngine.Calculate()","CalculationState + projections",true,true));c.Add(new("GUI-CMD-RECALCULATE-AFFECTED","GLOBAL",GuiControlKind.Button,"Calculation","RecalculateAffected","RecalculateAffected","DependencyGraph + RecalculationScheduler","Affected projections",true,false));c.Add(new("GUI-CMD-FORMULA-BAR","S05",GuiControlKind.FormulaBar,"Grid header","Edit formula / inspect formula","FormulaEditor","SelectedCell.Formula","FormulaTrace + dependency graph",true,false));c.Add(new("GUI-CMD-SOURCE-INSPECTOR","S08",GuiControlKind.Button,"Audit","Source inspector","InspectSource","CellBinding.Source","Source/provenance panel",true,false));c.Add(new("GUI-CMD-GOTO-CELL","S08",GuiControlKind.Button,"Audit","Go to cell","GoToCell","Sheet/Table/Row/Column","Selected GUI cell",true,false));c.Add(new("GUI-CMD-UNDO","GLOBAL",GuiControlKind.Button,"Document","Undo","Undo","RevisionState","Previous state",true,false));c.Add(new("GUI-CMD-REDO","GLOBAL",GuiControlKind.Button,"Document","Redo","Redo","RevisionState","Next state",true,false));c.Add(new("GUI-CMD-FILTER","S05",GuiControlKind.FilterBox,"Grid header","Filter rows","Filter","Current table query","Filtered projection",true,false));c.Add(new("GUI-SCROLL-V","ALL",GuiControlKind.VerticalScrollBar,"Each grid","Vertical scrolling","Scroll","Viewport only","Viewport",true,true));c.Add(new("GUI-SCROLL-H","ALL",GuiControlKind.HorizontalScrollBar,"Each grid","Horizontal scrolling","Scroll","Viewport only","Viewport",true,true));c.Add(new("GUI-SUBTABLE-EXPAND","ALL",GuiControlKind.SubTable,"Grid row","Expand detail","ExpandDetail","RowKey","Detail projection",true,false));c.Add(new("GUI-SHEET-NAV","GLOBAL",GuiControlKind.Tab,"Bottom workbook strip","Navigate sheets","SelectSheet","SheetId","Workspace",true,true));c.Add(new("GUI-SPLITTER","ALL",GuiControlKind.Splitter,"Main workspace","Resize main/subtable","Resize","LayoutState","Viewport layout",true,true));c.Add(new("GUI-STATUS","GLOBAL",GuiControlKind.StatusBar,"Bottom status","State/version/provenance","ShowStatus","CalculationState.Version","Status bar",true,false));}
}
public sealed record EsconSheetMapEntry(string EsconSheet,string DtbkSheet,string Domain,string PrimaryTable,string PrimarySource);
public static class EsconSheetMapV1{public static IReadOnlyList<EsconSheetMapEntry> All{get;}=new ReadOnlyCollection<EsconSheetMapEntry>(new EsconSheetMapEntry[]{new("TIÊN LƯỢNG","Dự toán","BOQ/Quantity","tblEstimateLines","ProjectItem + Takeoff"),new("GIÁ VẬT TƯ","Vật tư","Material Price","tblMaterialPrice","ResourcePriceProvider"),new("CƯỚC VCCG","Vật tư","Transport VCCG","tblTransportRate","TransportProvider"),new("CƯỚC VCTC","Vật tư","Transport VCTC","tblTransportRate","TransportProvider"),new("CƯỚC VCDT","Vật tư","Transport VCDT","tblTransportRate","TransportProvider"),new("CP TRUNG CHUYỂN","Vật tư","Transshipment","tblTransportRate","TransportProvider"),new("GIÁ NHÂN CÔNG","Vật tư","Labor Price","tblLaborPrice","LaborPriceProvider"),new("NCLM GỐC","Phân tích","Original Labor Norm","tblLabor","NormProvider"),new("NCLM HIỆN TẠI","Phân tích","Current Labor Norm","tblLabor","NormProvider + LaborPriceProvider"),new("PT MÁY","Phân tích","Machine Analysis","tblMachine","NormProvider + MachinePriceProvider"),new("TH MÁY","Vật tư","Machine Summary","tblMachinePrice","CalculationState.Resources"),new("PT BÙ GIÁ MÁY","Phân tích","Machine Adjustment Analysis","tblMachine","MachinePriceProvider"),new("TH BÙ GIÁ MÁY","Vật tư","Machine Adjustment Summary","tblMachinePrice","CalculationState.Resources"),new("PT VẬT TƯ","Phân tích","Material Analysis","tblMaterial","NormProvider + ResourcePriceProvider"),new("TH VẬT TƯ","Vật tư","Material Summary","tblMaterialPrice","CalculationState.Resources"),new("NHIÊN LIỆU, NCLM","Vật tư","Fuel/Labor Input","tblFuelPrice","FuelPriceProvider + LaborPriceProvider"),new("DG CÔNG TRÌNH","Thuyết minh","Project Unit Price Basis","tblPriceSource","PriceContext"),new("THKPHM","Tổng hợp","Cost Summary","tblSummary","CalculationState.Summary"),new("CP THIẾT BỊ","TH xây dựng","Equipment Cost","tblEquipment","EquipmentProvider"),new("CP XÂY DỰNG","TH xây dựng","Construction Cost","tblConstructionCost","CalculationState.Summary"),new("HẠNG MỤC CHUNG","TH xây dựng","General Items","tblIndirectCost","CalculationState.Summary"),new("DỰ PHÒNG PHÍ","Tổng hợp","Contingency","tblCostLayers","CalculationState.Summary"),new("TH KINH PHÍ","Tổng hợp","Funding Summary","tblSummary","CalculationState.Summary"),new("BÌA DỰ TOÁN","Bìa","Estimate Cover","tblCover","ProjectContext")});}
