namespace DTBK.Domain;
public enum WorkType{Civil=1,Industrial=2,Traffic=3,Infrastructure=4,Irrigation=5} public enum CalculationScenario{Construction=1,Installation=2,Survey=3,Testing=4,Maintenance=5,Consulting=6} public enum LocationType{Normal=1,Mountain=2,Border=3,Offshore=4,Island=5} public enum RateType{Overhead=1,TemporaryHouse=2,UnspecifiedWork=3,TaxableIncome=4} public enum RateBaseType{DirectCost=1,DirectPlusIndirect=2,Custom=3} public enum InterpolationMethod{None=0,Linear=1} public enum ResourceType{Material=1,Labor=2,Machine=3} public enum ValidationSeverity{Info=1,Warning=2,Error=3} public enum RoundingMode{AwayFromZero=1,ToEven=2,Floor=3,Ceiling=4} public enum DataPackageType{Full=1,Patch=2,Legal=3,Norm=4,Price=5,LaborPrice=6,Mixed=7} public enum CoefficientType{Location=1,Difficulty=2,Seasonal=3,Quality=4,Complexity=5,Other=9}
public sealed record Project(long ProjectID,string ProjectCode,string ProjectName,string Investor="",string Contractor="",string Location="",WorkType WorkType=WorkType.Civil,CalculationScenario Scenario=CalculationScenario.Construction,LocationType LocationType=LocationType.Normal,int? ProvinceID=null,DateTime CalculationDate=default,string Notes="");
public sealed record ProjectItem(long ProjectItemID,long ProjectID,string WorkCode,string Description,string Unit,decimal Quantity,string NormCode="",int SortOrder=0,decimal MaterialAmount=0m,decimal LaborAmount=0m,decimal MachineAmount=0m);
public sealed record CostLine(long ProjectItemID,string WorkCode,string Description,string Unit,decimal Quantity,decimal Material,decimal Labor,decimal Machine,string NormCode="");
public sealed record ProjectCostSummary{public decimal DirectMaterial{get;init;}public decimal DirectLabor{get;init;}public decimal DirectMachine{get;init;}public decimal DirectTransport{get;init;}public decimal DirectCost{get;init;}public decimal Overhead{get;init;}public decimal TemporaryHouse{get;init;}public decimal UnspecifiedWork{get;init;}public decimal IndirectCost{get;init;}public decimal TaxableIncome{get;init;}public decimal ConstructionCostBeforeTax{get;init;}public decimal VAT{get;init;}public decimal TotalConstructionCost{get;init;}public decimal OverheadRate{get;init;}public decimal TemporaryHouseRate{get;init;}public decimal UnspecifiedWorkRate{get;init;}public decimal TaxableIncomeRate{get;init;}public decimal VATRate{get;init;}public decimal AppliedCoefficient{get;init;}=1.0m;public string LegalVersion{get;init;}="DATA-PACKAGE-REQUIRED";public string EngineVersion{get;init;}="2.7.0";public string AppliedScenario{get;init;}="";public string LocationCode{get;init;}="";public IReadOnlyList<string> AppliedCoefficients{get;init;}=Array.Empty<string>();public IReadOnlyList<CalculationProvenance> RuleProvenance{get;init;}=Array.Empty<CalculationProvenance>();}
public sealed record Norm(long NormID,string NormCode,string WorkCode,string Name,string Unit,string WorkDescription="",string ApplicationNote="",string Appendix="",string Chapter="",bool IsActive=true);
public sealed record NormDetail(long NormDetailID,long NormID,ResourceType ResourceType,string ResourceCode,string ResourceName,string Unit,decimal Quantity,decimal? Percentage=null,string LaborGroup="",string Note="");
public sealed record LaborGroup(long LaborGroupID,string GroupCode,string GroupName,string Description="",int SortOrder=0,bool IsActive=true);
public sealed record LaborPrice(long LaborPriceID,long LaborGroupID,int ProvinceID,DateTime PriceDate,decimal UnitPrice,string Currency="VND",string SourceReference="",bool IsOfficial=true,DateTime? EffectiveFrom=null,DateTime? EffectiveTo=null);
public sealed record RateRule(long RateRuleID,long LegalBasisID,RateType RateType,WorkType WorkType,CalculationScenario Scenario,decimal MinBase,decimal? MaxBase,decimal Rate,LocationType Location,string SpecialCondition,bool InterpolationAllowed,RateBaseType BaseType=RateBaseType.DirectCost,InterpolationMethod InterpolationMethod=InterpolationMethod.None,long? AppendixID=null,string RuleCode="",int Priority=0,long? RoundingPolicyID=null,DateTime? EffectiveFrom=null,DateTime? EffectiveTo=null);
public sealed record VATRule(long VATRuleID,long LegalBasisID,decimal Rate,DateTime EffectiveFrom,DateTime? EffectiveTo,string Category);
public sealed record RoundingPolicy(long RoundingPolicyID,string PolicyCode,string Name,int QuantityScale,int RateScale,int CurrencyScale,RoundingMode Mode,bool IsActive);
public sealed record Province(long ProvinceID,string Code,string Name,bool IsActive=true); public sealed record DataVersion(long DataVersionID,string VersionCode,DataPackageType PackageType,DateTime CreatedAt,DateTime? EffectiveFrom,DateTime? EffectiveTo,string SourceHash,string Description);
public sealed record CoefficientRule(long CoefficientRuleID,CoefficientType Type,string Code,string Name,decimal Factor,WorkType? ApplicableWorkType,LocationType? ApplicableLocation,string Description,string LegalBasis,bool IsActive=true,int Priority=0,DateTime? EffectiveFrom=null,DateTime? EffectiveTo=null);
public sealed record CoefficientSet(IReadOnlyList<CoefficientRule> Rules){public decimal TotalFactor=>Rules.Where(r=>r.IsActive).Aggregate(1.0m,(acc,r)=>acc*r.Factor);public IReadOnlyList<string> Descriptions=>Rules.Where(r=>r.IsActive).Select(r=>$"{r.Name} ({r.Factor:0.####})").ToList();}
public sealed record ReportRequest(string ProjectName,string Investor,string Contractor,string Location,DateTime CalculationDate,ProjectCostSummary Summary,IReadOnlyList<CostLine> Lines,string PreparedBy="",string CheckedBy="",CalculationState? State=null); public sealed record ReportResult(string Title,string Content,string Format="text/plain");
public sealed record ValidationIssue(ValidationSeverity Severity,string Code,string Message,long? ProjectItemID=null,string? Context=null); public sealed record ValidationResult(IReadOnlyList<ValidationIssue> Issues){public bool IsValid=>Issues.All(x=>x.Severity!=ValidationSeverity.Error);public IEnumerable<ValidationIssue> Errors=>Issues.Where(x=>x.Severity==ValidationSeverity.Error);public IEnumerable<ValidationIssue> Warnings=>Issues.Where(x=>x.Severity==ValidationSeverity.Warning);}
public sealed record CalculationExplanation(string ResultCode,decimal Value,string FormulaRuntime,IReadOnlyList<string> Inputs,IReadOnlyList<string> AppliedRules,IReadOnlyList<string> LegalBases,IReadOnlyList<string> PriceSources,string RoundingPolicy,string Narrative);
public interface IRateResolver{RateRule Resolve(RateType type,WorkType workType,CalculationScenario scenario,LocationType location,decimal baseValue,DateTime effectiveDate);VATRule ResolveVat(DateTime effectiveDate,string category="STANDARD");}
public interface ILaborPriceProvider{LaborPrice ResolvePrice(string groupCode,int provinceId,DateTime date);IReadOnlyList<LaborPrice> ResolveMany(IEnumerable<(string GroupCode,int ProvinceId,DateTime Date)> keys);}
public sealed record LaborPriceImportCommand(string PackageJson,string SourceHash,string OriginalFileName); public sealed record LaborPriceCommitResult(int SuccessCount,int ErrorCount,long DataVersionID,IReadOnlyList<string> Errors); public interface ILaborPriceImportStore{LaborPriceCommitResult Commit(LaborPriceImportCommand command);}
public interface INormProvider{Norm? GetNorm(string normCode);IReadOnlyList<NormDetail> GetNormDetails(long normId);} public interface ILaborGroupProvider{LaborGroup? GetByCode(string groupCode);IReadOnlyList<LaborGroup> GetActiveGroups();} public interface IResourcePriceProvider{decimal ResolveUnitPrice(ResourceType type,string resourceCode,int provinceId,DateTime date);} public interface ICoefficientProvider{CoefficientSet Resolve(WorkType workType,LocationType location,DateTime effectiveDate,IEnumerable<string>? extraCodes=null);}
public sealed record ResourceConsumption(string ResourceCode,string ResourceName,ResourceType Type,string Unit,decimal Quantity,string LaborGroup,decimal? UnitPrice,decimal? Amount,bool IsOtherMaterial,decimal? Percentage,string SourceNormDetail);
public sealed record NormWorkerGroup(long WorkerGroupId,string GroupCode,string FullName,string Description,DateTime EffectiveFrom,DateTime? EffectiveTo=null,long? LegalReferenceId=null,string SourceHash="",bool IsActive=true); public sealed record WorkerGroupMapping(long WorkTaskId,long WorkerGroupId,string MappingRule,string EvidenceReference="",long? LegalReferenceId=null,DateTime? EffectiveFrom=null,DateTime? EffectiveTo=null,string SourceHash=""); public sealed record NormWorkerGroupPrice(long WorkerGroupPriceId,long WorkerGroupId,decimal Price,string ProvinceCode,DateTime EffectiveFrom,DateTime? EffectiveTo,DateTime? PublishedDate,string Currency,string SourceReference,string SourceHash,bool IsOfficial,long? DataVersionId=null); public sealed record LegalReferenceVersion(long LegalReferenceVersionId,long LegalReferenceId,string VersionCode,DateTime EffectiveFrom,DateTime? EffectiveTo,string SourceUri,string SourceHash,DateTime CapturedAt,string Notes=""); public sealed record ContractTemplate(long ContractTemplateId,string TemplateCode,string TemplateName,string AppendixCode,long? LegalReferenceId,string OfficialSourceUri,bool IsOfficialTextIncluded,bool IsActive);
public sealed record ContractAdjustmentRequest(decimal OriginalContractValue,string BasePeriod,string AdjustmentPeriod,string AdjustmentMethod,decimal? MaterialIndex,decimal? LaborIndex,decimal? MachineIndex,decimal? BaseMaterialIndex=null,decimal? BaseLaborIndex=null,decimal? BaseMachineIndex=null,long? ContractInstanceId=null,long? LegalReferenceId=null);
public sealed record ContractAdjustmentResult(decimal OriginalContractValue,decimal AdjustmentFactor,decimal AdjustedValue,decimal AdjustmentAmount,string FormulaCode,string Status,IReadOnlyList<string> Breakdown,string EvidenceHash,string LegalBasis); public sealed record LegalComplianceCheckResult(string RuleCode,string Result,string Message,string InputHash,string OutputHash,string EvidenceHash,long? LegalReferenceId=null); public interface IContractAdjustmentEngine{ContractAdjustmentResult Calculate(ContractAdjustmentRequest request);}
public interface IDigitalSignatureProvider{string ProviderCode{get;}DigitalSignatureResult Sign(ReadOnlyMemory<byte> document,DigitalSignatureRequest request);DigitalSignatureVerification Verify(ReadOnlyMemory<byte> document,DigitalSignatureResult signature);} public sealed record DigitalSignatureRequest(string DocumentHash,string SignatureAlgorithm="SHA256withRSA"); public sealed record DigitalSignatureResult(string ProviderCode,string DocumentHash,string SignatureAlgorithm,string CertificateSerial,string CertificateSubject,string SignatureValueBase64,DateTime SignedAt); public sealed record DigitalSignatureVerification(bool IsValid,string Status,string Message);
public sealed record DigitalSignatureApiRequest(string DocumentName,string DocumentHash,string SignatureAlgorithm="SHA256withRSA",string SignerRole="",string CallbackReference=""); public sealed record DigitalSignatureApiResult(string ProviderCode,string DocumentHash,string SignatureAlgorithm,string SignatureValueBase64,string CertificateSerial,string CertificateSubject,DateTime? SignedAtUtc,string TimestampTokenBase64="",string ExternalReference="");
public sealed record AccountingRecognitionRequest(decimal ContractRevenue,decimal CumulativeCostsToDate,decimal EstimatedTotalContractCosts,decimal PriorRecognizedRevenue,decimal CurrentPeriodCosts,string MeasurementMethod="COST_TO_COST",decimal? AssessedCompletionPercent=null,decimal? CompletedQuantity=null,decimal? TotalQuantity=null,bool OutcomeReliablyEstimable=true,bool CostsRecoverable=true,DateTime RecognitionDate=default); public sealed record AccountingRecognitionResult(string StandardCode,string MeasurementMethod,decimal CompletionPercent,decimal CumulativeRevenue,decimal CurrentPeriodRevenue,decimal CurrentPeriodCost,decimal CurrentPeriodGrossResult,decimal ExpectedContractLoss,bool LossRecognizedImmediately,string Status,IReadOnlyList<string> Notes); public interface IConstructionAccountingEngine{AccountingRecognitionResult Calculate(AccountingRecognitionRequest request);} public interface IDigitalSignatureApiProvider{string ProviderCode{get;}Task<DigitalSignatureApiResult> SignAsync(ReadOnlyMemory<byte> document,DigitalSignatureApiRequest request,CancellationToken cancellationToken=default);Task<DigitalSignatureVerification> VerifyAsync(ReadOnlyMemory<byte> document,DigitalSignatureApiResult signature,CancellationToken cancellationToken=default);}
