namespace DTBK.Engine;

public sealed record SemanticColumn(string Id, string DataType, bool FormulaAllowed, bool ReadOnly);
public sealed record SemanticTable(string Id, string Purpose, IReadOnlyList<SemanticColumn> Columns);
public sealed record SemanticSheet(string Id, int Order, string Purpose, IReadOnlyList<SemanticTable> Tables);

/// <summary>
/// Canonical 15-sheet domain contract. The registry is intentionally domain-specific:
/// every sheet declares its main table and required supporting tables/columns.
/// Calculation remains canonical in CalculationStateEngine; sheets are projections except
/// explicitly editable input tables.
/// </summary>
public sealed class Canonical15SheetSemanticRegistry
{
    private readonly IReadOnlyList<SemanticSheet> _sheets;

    public Canonical15SheetSemanticRegistry()
    {
        _sheets = new[]
        {
            Sheet("S01", 1, "BOQ / Khối lượng", Table("BOQ", "Công tác và khối lượng", C("STT","int",false,true), C("GROUP_CODE","string",false,false), C("WORK_CODE","string",false,false), C("WORK_NAME","string",false,false), C("DESCRIPTION","string",false,false), C("UNIT","string",false,false), C("QUANTITY","decimal",true,false), C("UNIT_PRICE_REF","decimal",false,true), C("AMOUNT","decimal",true,true), C("NORM_CODE","string",false,false), C("RESOURCE_GROUP","string",false,true), C("NOTE","string",false,false), C("SOURCE_REF","string",false,true), C("OVERRIDE_FLAG","bool",false,false)), Table("QUANTITY_DETAIL", "Công thức/chi tiết đo bóc", C("ROW_ID","string",false,true), C("DIMENSION","string",false,false), C("L1","decimal",true,false), C("L2","decimal",true,false), C("L3","decimal",true,false), C("L4","decimal",true,false), C("FACTOR","decimal",true,false), C("FORMULA","string",false,false), C("QUANTITY","decimal",true,true), C("SOURCE_REF","string",false,true)), Table("WORK_GROUP", "Cây nhóm công tác", C("GROUP_CODE","string",false,false), C("PARENT_CODE","string",false,false), C("NAME","string",false,false), C("LEVEL","int",false,true)), Table("NORM_SELECTION", "Định mức được chọn", C("WORK_CODE","string",false,true), C("NORM_CODE","string",false,false), C("VARIANT","string",false,false), C("EFFECTIVE_FROM","date",false,true), C("EFFECTIVE_TO","date",false,true), C("SOURCE_REF","string",false,true)), Table("OVERRIDE", "Ghi đè có giải trình", C("CELL_REF","string",false,true), C("VALUE","decimal",false,false), C("REASON","string",false,false), C("AUTHOR","string",false,true), C("TIMESTAMP","datetime",false,true))),
            Sheet("S02", 2, "Phân tích khối lượng", Table("TAKEOFF", "Takeoff và diễn giải", C("STT","int",false,true), C("GROUP_CODE","string",false,false), C("WORK_CODE","string",false,false), C("ITEM","string",false,false), C("DESCRIPTION","string",false,false), C("UNIT","string",false,false), C("L1","decimal",true,false), C("L2","decimal",true,false), C("L3","decimal",true,false), C("L4","decimal",true,false), C("FACTOR","decimal",true,false), C("QUANTITY","decimal",true,true), C("FORMULA","string",false,false), C("SOURCE_REF","string",false,true), C("NOTE","string",false,false)), Table("DRAWING_SOURCE", "Nguồn đo bóc", C("SOURCE_REF","string",false,true), C("SOURCE_TYPE","string",false,true), C("LOCATION","string",false,true), C("DESCRIPTION","string",false,false)), Table("QUANTITY_GROUP", "Tổng hợp nhóm", C("GROUP_CODE","string",false,true), C("GROUP_NAME","string",false,true), C("QUANTITY","decimal",true,true), C("UNIT","string",false,true))),
            Sheet("S03", 3, "Tổng hợp kinh phí", Table("SUMMARY", "Tổng hợp chi phí", C("STT","int",false,true), C("COST_GROUP","string",false,true), C("COST_CODE","string",false,true), C("CONTENT","string",false,true), C("PRE_TAX","decimal",true,true), C("VAT","decimal",true,true), C("POST_TAX","decimal",true,true), C("RATE","decimal",true,true), C("BASIS","decimal",true,true), C("SOURCE_REF","string",false,true)), Table("COST_COMPONENT", "Chi tiết thành phần chi phí", C("CODE","string",false,true), C("NAME","string",false,true), C("VALUE","decimal",true,true), C("SOURCE_SHEET","string",false,true)), Table("VAT", "Thuế GTGT", C("BASIS","decimal",true,true), C("RATE","decimal",false,true), C("VALUE","decimal",true,true)), Table("CONTINGENCY", "Dự phòng", C("BASIS","decimal",true,true), C("RATE","decimal",false,true), C("VALUE","decimal",true,true))),
            Sheet("S04", 4, "Hệ số", Table("COEFFICIENT", "Hệ số áp dụng", C("CODE","string",false,false), C("NAME","string",false,false), C("TYPE","string",false,false), C("VALUE","decimal",true,false), C("UNIT","string",false,true), C("BASIS","decimal",true,true), C("SCOPE","string",false,false), C("EFFECTIVE_FROM","date",false,true), C("EFFECTIVE_TO","date",false,true), C("SOURCE_REF","string",false,true), C("FORMULA_REF","string",false,true), C("OVERRIDE_FLAG","bool",false,false)), Table("RATE_SET", "Bộ tỷ lệ theo phạm vi", C("CODE","string",false,true), C("NAME","string",false,true), C("RATE","decimal",false,true), C("SCOPE","string",false,true), C("SOURCE_REF","string",false,true)), Table("OVERRIDE", "Hệ số tùy chỉnh", C("CODE","string",false,true), C("VALUE","decimal",false,false), C("REASON","string",false,false), C("SOURCE_REF","string",false,true))),
            Sheet("S05", 5, "Đơn giá công tác", Table("UNIT_PRICE", "Đơn giá và thành tiền", C("WORK_CODE","string",false,true), C("WORK_NAME","string",false,true), C("UNIT","string",false,true), C("QUANTITY","decimal",true,true), C("MATERIAL_COST","decimal",true,true), C("LABOR_COST","decimal",true,true), C("MACHINE_COST","decimal",true,true), C("TRANSPORT_COST","decimal",true,true), C("OTHER_COST","decimal",true,true), C("DIRECT_COST","decimal",true,true), C("UNIT_PRICE","decimal",true,true), C("AMOUNT","decimal",true,true), C("NORM_REF","string",false,true), C("PRICE_REF","string",false,true), C("FORMULA_REF","string",false,true)), Table("MATERIAL_COMPONENT", "Phân tích vật liệu", C("WORK_CODE","string",false,true), C("RESOURCE_CODE","string",false,true), C("RESOURCE_NAME","string",false,true), C("UNIT","string",false,true), C("COEFFICIENT","decimal",true,true), C("PRICE","decimal",true,true), C("AMOUNT","decimal",true,true)), Table("LABOR_COMPONENT", "Phân tích nhân công", C("WORK_CODE","string",false,true), C("RESOURCE_CODE","string",false,true), C("RESOURCE_NAME","string",false,true), C("UNIT","string",false,true), C("COEFFICIENT","decimal",true,true), C("PRICE","decimal",true,true), C("AMOUNT","decimal",true,true)), Table("MACHINE_COMPONENT", "Phân tích máy", C("WORK_CODE","string",false,true), C("RESOURCE_CODE","string",false,true), C("RESOURCE_NAME","string",false,true), C("UNIT","string",false,true), C("COEFFICIENT","decimal",true,true), C("PRICE","decimal",true,true), C("AMOUNT","decimal",true,true)), Table("TRANSPORT_COMPONENT", "Phân tích cước", C("WORK_CODE","string",false,true), C("TRANSPORT_CODE","string",false,true), C("DISTANCE","decimal",true,true), C("RATE","decimal",true,true), C("AMOUNT","decimal",true,true))),
            Sheet("S06", 6, "Yêu cầu tài nguyên", Table("RESOURCE_REQUIREMENTS", "Vật tư/NC/Máy/Nhiên liệu/Cước", C("WORK_CODE","string",false,true), C("RESOURCE_TYPE","string",false,true), C("RESOURCE_CODE","string",false,true), C("RESOURCE_NAME","string",false,true), C("UNIT","string",false,true), C("COEFFICIENT","decimal",true,true), C("QUANTITY","decimal",true,true), C("PRICE_REF","decimal",true,true), C("AMOUNT","decimal",true,true), C("NORM_REF","string",false,true), C("SOURCE_REF","string",false,true)), Table("MATERIAL", "Yêu cầu vật liệu", C("RESOURCE_CODE","string",false,true), C("QUANTITY","decimal",true,true), C("UNIT","string",false,true)), Table("LABOR", "Yêu cầu nhân công", C("RESOURCE_CODE","string",false,true), C("QUANTITY","decimal",true,true), C("UNIT","string",false,true)), Table("MACHINE", "Yêu cầu máy", C("RESOURCE_CODE","string",false,true), C("QUANTITY","decimal",true,true), C("UNIT","string",false,true)), Table("FUEL", "Nhiên liệu/năng lượng", C("RESOURCE_CODE","string",false,true), C("QUANTITY","decimal",true,true), C("UNIT","string",false,true)), Table("TRANSPORT", "Yêu cầu vận chuyển", C("TRANSPORT_CODE","string",false,true), C("DISTANCE","decimal",true,true), C("QUANTITY","decimal",true,true), C("AMOUNT","decimal",true,true))),
            Sheet("S07", 7, "Giá tài nguyên", Table("RESOURCE_PRICES", "Giá theo loại và nguồn", C("RESOURCE_TYPE","string",false,false), C("CODE","string",false,false), C("NAME","string",false,false), C("UNIT","string",false,false), C("LOCATION","string",false,false), C("PRICE","decimal",false,false), C("PRICE_TYPE","string",false,false), C("EFFECTIVE_FROM","date",false,false), C("EFFECTIVE_TO","date",false,false), C("SOURCE_DOCUMENT","string",false,true), C("SOURCE_REF","string",false,true), C("VERSION","string",false,true), C("SELECTED_FLAG","bool",false,false), C("OVERRIDE_FLAG","bool",false,false)), Table("MATERIAL_PRICE", "Giá vật liệu", C("CODE","string",false,false), C("NAME","string",false,false), C("UNIT","string",false,false), C("LOCATION","string",false,false), C("PRICE","decimal",false,false), C("SOURCE_REF","string",false,true)), Table("LABOR_PRICE", "Giá nhân công", C("CODE","string",false,false), C("GRADE","string",false,false), C("GROUP","string",false,false), C("LOCATION","string",false,false), C("PRICE","decimal",false,false), C("SOURCE_REF","string",false,true)), Table("MACHINE_PRICE", "Giá ca máy", C("CODE","string",false,false), C("NAME","string",false,false), C("UNIT","string",false,false), C("LOCATION","string",false,false), C("RATE","decimal",false,false), C("SOURCE_REF","string",false,true)), Table("FUEL_PRICE", "Giá nhiên liệu/năng lượng", C("CODE","string",false,false), C("NAME","string",false,false), C("UNIT","string",false,false), C("PRICE","decimal",false,false), C("SOURCE_REF","string",false,true))),
            Sheet("S08", 8, "Định mức", Table("NORMS", "Định mức và hao phí", C("NORM_CODE","string",false,false), C("NORM_NAME","string",false,false), C("UNIT","string",false,false), C("WORK_TYPE","string",false,false), C("VERSION","string",false,true), C("EFFECTIVE_FROM","date",false,true), C("EFFECTIVE_TO","date",false,true), C("SOURCE_DOCUMENT","string",false,true), C("SCOPE","string",false,false), C("NOTES","string",false,false)), Table("NORM_DETAIL", "Hao phí theo tài nguyên", C("NORM_CODE","string",false,true), C("RESOURCE_TYPE","string",false,true), C("RESOURCE_CODE","string",false,true), C("RESOURCE_NAME","string",false,true), C("UNIT","string",false,true), C("COEFFICIENT","decimal",true,true), C("WASTE_LOSS","decimal",true,true), C("PERCENT_FLAG","bool",false,true)), Table("NORM_VARIANT", "Biến thể/thay thế", C("NORM_CODE","string",false,true), C("VARIANT_CODE","string",false,true), C("DESCRIPTION","string",false,true), C("SOURCE_REF","string",false,true)), Table("NORM_HISTORY", "Lịch sử định mức", C("NORM_CODE","string",false,true), C("VERSION","string",false,true), C("EFFECTIVE_FROM","date",false,true), C("EFFECTIVE_TO","date",false,true), C("SOURCE_REF","string",false,true))),
            Sheet("S09", 9, "Cước vận chuyển", Table("TRANSPORT", "Nguồn-đích-cự ly-cước", C("CODE","string",false,false), C("MATERIAL_CODE","string",false,false), C("MATERIAL_NAME","string",false,false), C("UNIT","string",false,false), C("SOURCE","string",false,false), C("DESTINATION","string",false,false), C("DISTANCE","decimal",true,false), C("ROUTE_TYPE","string",false,false), C("VEHICLE_TYPE","string",false,false), C("LOAD","decimal",true,false), C("RATE","decimal",true,false), C("FUEL_FACTOR","decimal",true,false), C("LABOR_FACTOR","decimal",true,false), C("COST","decimal",true,true), C("SOURCE_REF","string",false,true), C("EFFECTIVE_FROM","date",false,true), C("EFFECTIVE_TO","date",false,true)), Table("ROUTE", "Đoạn tuyến", C("ROUTE_ID","string",false,true), C("FROM","string",false,false), C("TO","string",false,false), C("DISTANCE","decimal",true,false), C("ROUTE_TYPE","string",false,false)), Table("RATE_BAND", "Bậc cự ly/cước", C("CODE","string",false,true), C("MIN_DISTANCE","decimal",false,true), C("MAX_DISTANCE","decimal",false,true), C("RATE","decimal",false,true), C("SOURCE_REF","string",false,true)), Table("FUEL_ASSUMPTION", "Giả định nhiên liệu", C("FUEL_CODE","string",false,true), C("CONSUMPTION","decimal",false,true), C("PRICE","decimal",false,true), C("SOURCE_REF","string",false,true))),
            Sheet("S10", 10, "Giải trình", Table("EXPLAIN", "Formula/source/provenance", C("CELL_REF","string",false,true), C("SHEET_REF","string",false,true), C("LABEL","string",false,true), C("VALUE","string",false,true), C("FORMULA","string",false,true), C("DEPENDENCY","string",false,true), C("PROVIDER","string",false,true), C("SOURCE_REF","string",false,true), C("RULE_REF","string",false,true), C("CALCULATION_STEP","string",false,true), C("STATUS","string",false,true)), Table("DEPENDENCY", "Nguồn phụ thuộc", C("CELL_REF","string",false,true), C("UPSTREAM_CELL","string",false,true), C("EDGE_TYPE","string",false,true)), Table("PROVENANCE", "Truy nguyên nguồn", C("CELL_REF","string",false,true), C("SOURCE_ID","string",false,true), C("SOURCE_VERSION","string",false,true), C("SOURCE_OFFSET","string",false,true), C("EVIDENCE_REF","string",false,true))),
            Sheet("S11", 11, "Kiểm tra", Table("AUDIT", "Reconciliation và validation", C("CHECK_ID","string",false,true), C("SEVERITY","string",false,true), C("CATEGORY","string",false,true), C("SHEET_REF","string",false,true), C("CELL_REF","string",false,true), C("EXPECTED","string",false,true), C("ACTUAL","string",false,true), C("DIFFERENCE","decimal",true,true), C("RULE_REF","string",false,true), C("SOURCE_REF","string",false,true), C("STATUS","string",false,true), C("MESSAGE","string",false,true)), Table("QUANTITY_CHECK", "Đối soát khối lượng", C("WORK_CODE","string",false,true), C("EXPECTED","decimal",false,true), C("ACTUAL","decimal",false,true), C("DIFFERENCE","decimal",true,true), C("STATUS","string",false,true)), Table("FORMULA_CHECK", "Kiểm tra công thức/đồ thị", C("CELL_REF","string",false,true), C("FORMULA","string",false,true), C("DEPENDENCY_COUNT","int",false,true), C("CYCLE_FLAG","bool",false,true), C("STATUS","string",false,true)), Table("LEGAL_CHECK", "Áp dụng pháp lý", C("RULE_REF","string",false,true), C("EFFECTIVE_DATE","date",false,true), C("SCOPE","string",false,true), C("STATUS","string",false,true))),
            Sheet("S12", 12, "Phân tích", Table("ANALYSIS", "Phân tích theo nhóm", C("GROUP_CODE","string",false,true), C("GROUP_NAME","string",false,true), C("RESOURCE_TYPE","string",false,true), C("QUANTITY","decimal",true,true), C("UNIT","string",false,true), C("UNIT_COST","decimal",true,true), C("TOTAL_COST","decimal",true,true), C("SHARE_PERCENT","decimal",true,true), C("VARIANCE","decimal",true,true), C("BASIS","decimal",true,true)), Table("COST_BY_RESOURCE", "Chi phí theo loại tài nguyên", C("RESOURCE_TYPE","string",false,true), C("VALUE","decimal",true,true), C("SHARE_PERCENT","decimal",true,true)), Table("VARIANCE", "Phân tích chênh lệch", C("CODE","string",false,true), C("BASELINE","decimal",false,true), C("CURRENT","decimal",false,true), C("VARIANCE","decimal",true,true), C("VARIANCE_PERCENT","decimal",true,true))),
            Sheet("S13", 13, "Dự thầu", Table("BID", "Giá dự thầu", C("WORK_CODE","string",false,true), C("WORK_NAME","string",false,true), C("UNIT","string",false,true), C("ESTIMATE_QTY","decimal",true,true), C("ESTIMATE_UNIT_PRICE","decimal",true,true), C("ESTIMATE_AMOUNT","decimal",true,true), C("BID_UNIT_PRICE","decimal",false,false), C("BID_AMOUNT","decimal",true,true), C("ADJUSTMENT","decimal",false,false), C("DISCOUNT","decimal",false,false), C("TAX","decimal",true,true), C("TOTAL","decimal",true,true), C("BASIS","string",false,false), C("OVERRIDE_FLAG","bool",false,false)), Table("BID_ADJUSTMENT", "Điều chỉnh dự thầu", C("WORK_CODE","string",false,true), C("TYPE","string",false,false), C("VALUE","decimal",false,false), C("REASON","string",false,false)), Table("BID_SUMMARY", "Tổng hợp dự thầu", C("GROUP_CODE","string",false,true), C("PRE_TAX","decimal",true,true), C("TAX","decimal",true,true), C("TOTAL","decimal",true,true))),
            Sheet("S14", 14, "Hợp đồng/phát sinh/thanh toán/quyết toán", Table("COMMERCIAL", "Contract/variation/payment", C("ITEM_CODE","string",false,true), C("ITEM_NAME","string",false,true), C("CONTRACT_QTY","decimal",false,false), C("CONTRACT_RATE","decimal",false,false), C("CONTRACT_AMOUNT","decimal",true,true), C("VARIATION_QTY","decimal",false,false), C("VARIATION_RATE","decimal",false,false), C("VARIATION_AMOUNT","decimal",true,true), C("EXECUTED_QTY","decimal",false,false), C("PAYMENT_QTY","decimal",false,false), C("PAYMENT_AMOUNT","decimal",true,true), C("SETTLEMENT_QTY","decimal",false,false), C("SETTLEMENT_AMOUNT","decimal",true,true), C("STATUS","string",false,false), C("SOURCE_REF","string",false,true)), Table("CONTRACT", "Giá trị hợp đồng gốc", C("ITEM_CODE","string",false,true), C("QTY","decimal",false,false), C("RATE","decimal",false,false), C("AMOUNT","decimal",true,true), C("SNAPSHOT_ID","string",false,true)), Table("VARIATION", "Phát sinh/thay đổi", C("ITEM_CODE","string",false,true), C("QTY","decimal",false,false), C("RATE","decimal",false,false), C("AMOUNT","decimal",true,true), C("APPROVAL_REF","string",false,true)), Table("PAYMENT", "Thanh toán", C("PERIOD","string",false,false), C("EXECUTED_QTY","decimal",false,false), C("PAYMENT_AMOUNT","decimal",true,true), C("SOURCE_REF","string",false,true)), Table("SETTLEMENT", "Quyết toán", C("ITEM_CODE","string",false,true), C("SETTLEMENT_QTY","decimal",false,false), C("SETTLEMENT_AMOUNT","decimal",true,true), C("STATUS","string",false,false))),
            Sheet("S15", 15, "Báo cáo", Table("REPORT", "Projection/export từ CalculationState", C("REPORT_ID","string",false,true), C("REPORT_TYPE","string",false,true), C("SHEET_REF","string",false,true), C("SECTION","string",false,true), C("ROW_CODE","string",false,true), C("LABEL","string",false,true), C("VALUE","string",false,true), C("UNIT","string",false,true), C("SOURCE_STATE","string",false,true), C("SOURCE_REF","string",false,true), C("GENERATED_AT","datetime",false,true), C("VERSION","string",false,true)), Table("ESTIMATE_REPORT", "Báo cáo dự toán", C("ROW_CODE","string",false,true), C("LABEL","string",false,true), C("VALUE","decimal",true,true), C("UNIT","string",false,true)), Table("RESOURCE_REPORT", "Báo cáo tài nguyên", C("RESOURCE_TYPE","string",false,true), C("CODE","string",false,true), C("NAME","string",false,true), C("QUANTITY","decimal",true,true), C("VALUE","decimal",true,true)), Table("COMMERCIAL_REPORT", "Báo cáo thương mại", C("STAGE","string",false,true), C("CODE","string",false,true), C("VALUE","decimal",true,true)), Table("AUDIT_REPORT", "Báo cáo kiểm tra/giải trình", C("CHECK_ID","string",false,true), C("STATUS","string",false,true), C("MESSAGE","string",false,true)))
        };
    }

    public IReadOnlyList<SemanticSheet> Sheets => _sheets;
    public SemanticSheet Get(string sheetId) => _sheets.FirstOrDefault(x => string.Equals(x.Id, sheetId, StringComparison.OrdinalIgnoreCase)) ?? throw new KeyNotFoundException($"Unknown canonical sheet: {sheetId}");
    private static SemanticSheet Sheet(string id, int order, string purpose, params SemanticTable[] tables) => new(id, order, purpose, tables);
    private static SemanticTable Table(string id, string purpose, params SemanticColumn[] columns) => new(id, purpose, columns);
    private static SemanticColumn C(string id, string dataType, bool formulaAllowed, bool readOnly) => new(id, dataType, formulaAllowed, readOnly);
}
