using System.Globalization;
using DTBK.Domain;

namespace DTBK.Engine;

/// <summary>CostX/Vietnam-style QTO worksheet kernel.</summary>
public sealed class CostXVietnamQtoEngine
{
    private readonly QuantityTakeoffEngine _geometry = new();
    public IReadOnlyList<ResolvedQtoDimension> ResolveWorksheet(QtoWorksheet worksheet)
    {
        ArgumentNullException.ThrowIfNull(worksheet); if (string.IsNullOrWhiteSpace(worksheet.WorksheetId)) throw new InvalidOperationException("QTO worksheet requires WorksheetId."); if (string.IsNullOrWhiteSpace(worksheet.RevisionId)) throw new InvalidOperationException("QTO worksheet requires RevisionId.");
        var ordered = worksheet.Dimensions.OrderBy(x => x.Sequence).ThenBy(x => x.DimensionId, StringComparer.Ordinal).ToList(); var byId = ordered.ToDictionary(x => x.DimensionId, StringComparer.OrdinalIgnoreCase); var state = new Dictionary<string, ResolutionState>(StringComparer.OrdinalIgnoreCase); var resolved = new Dictionary<string, ResolvedQtoDimension>(StringComparer.OrdinalIgnoreCase);
        foreach (var dimension in ordered) ResolveDimension(dimension, ordered, byId, state, resolved, worksheet.RevisionId); return ordered.Select(x => resolved[x.DimensionId]).ToArray();
    }
    public decimal EvaluateExpression(string expression, IReadOnlyDictionary<string, decimal>? variables = null)
    {
        if (string.IsNullOrWhiteSpace(expression)) throw new ArgumentException("QTO expression is required.", nameof(expression)); var values = variables ?? new Dictionary<string, decimal>(StringComparer.OrdinalIgnoreCase); var text = NormalizeArithmeticExpression(expression); var parser = new FormulaParser(text, name => { if (!values.TryGetValue(name, out var value)) throw new InvalidOperationException($"Unknown dimension reference '{name}'."); return value; }); return parser.Parse();
    }
    public Measurement CreateMeasurement(QtoDimension dimension, MeasurementGeometry geometry, DrawingCalibration calibration, string sourceHash, string evidenceHash)
    {
        ArgumentNullException.ThrowIfNull(dimension); ArgumentNullException.ThrowIfNull(geometry); ArgumentNullException.ThrowIfNull(calibration); decimal quantity = dimension.MeasurementType switch { MeasurementType.Length => _geometry.MeasureLength(geometry.Points, calibration), MeasurementType.Area => _geometry.MeasureArea(geometry.Points, calibration), MeasurementType.Count => _geometry.MeasureCount(geometry.Points.Count), MeasurementType.Volume => throw new InvalidOperationException("Volume requires an explicit area/depth formula; geometry alone is insufficient."), _ => throw new ArgumentOutOfRangeException(nameof(dimension.MeasurementType)) }; if (dimension.IsDeduction) quantity = -Math.Abs(quantity); return new Measurement(dimension.DimensionId, dimension.RevisionId, dimension.MeasurementType, geometry.Type, quantity, dimension.Unit, dimension.WorkCode, dimension.NormCode, dimension.DimensionId, geometry, sourceHash, evidenceHash, dimension.Expression, true);
    }
    public IReadOnlyList<QtoEstimateItem> BuildEstimateItems(QtoWorksheet worksheet, IReadOnlyDictionary<string, long> projectItemIds)
    {
        ArgumentNullException.ThrowIfNull(projectItemIds); var resolved = ResolveWorksheet(worksheet); var groups = resolved.GroupBy(x => new { x.Dimension.WorkCode, x.Dimension.NormCode, x.Dimension.Unit }).OrderBy(x => x.Key.WorkCode, StringComparer.Ordinal).ThenBy(x => x.Key.NormCode, StringComparer.Ordinal).ThenBy(x => x.Key.Unit, StringComparer.Ordinal); var result = new List<QtoEstimateItem>(); foreach (var group in groups) { var key = MakeItemKey(group.Key.WorkCode, group.Key.NormCode, group.Key.Unit); if (!projectItemIds.TryGetValue(key, out var projectItemId)) throw new InvalidOperationException($"No ProjectItemID mapping for QTO key: {key}"); var quantity = group.Sum(x => x.Quantity); var description = string.Join("; ", group.Select(x => x.Dimension.Description).Where(x => !string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.Ordinal)); result.Add(new QtoEstimateItem(projectItemId, group.Key.WorkCode, description, group.Key.Unit, quantity, group.Key.NormCode, group.Select(x => x.Dimension.DimensionId).ToArray())); } return result;
    }
    public IReadOnlyList<ProjectItem> ToProjectItems(QtoWorksheet worksheet, IReadOnlyDictionary<string, long> projectItemIds, long projectId) { if (projectId <= 0) throw new ArgumentOutOfRangeException(nameof(projectId)); return BuildEstimateItems(worksheet, projectItemIds).Select(x => new ProjectItem(x.ProjectItemId, projectId, x.WorkCode, x.Description, x.Unit, x.Quantity, x.NormCode)).ToArray(); }
    public QtoEstimateLinkResult LinkToVietnamEstimate(QtoWorksheet worksheet, IReadOnlyDictionary<string, long> projectItemIds, long projectId, NormCostBridge normCostBridge, int provinceId, DateTime priceDate) { ArgumentNullException.ThrowIfNull(normCostBridge); var items = ToProjectItems(worksheet, projectItemIds, projectId); var costLines = normCostBridge.Calculate(items, provinceId, priceDate); var evidenceHash = BuildEvidenceHash(worksheet, items, costLines); return new QtoEstimateLinkResult(items.Select(ToEstimateItem).ToArray(), costLines, worksheet.WorksheetId, worksheet.RevisionId, evidenceHash); }
    public static string MakeItemKey(string workCode, string normCode, string unit) { if (string.IsNullOrWhiteSpace(workCode)) throw new ArgumentException("WorkCode is required.", nameof(workCode)); if (string.IsNullOrWhiteSpace(normCode)) throw new ArgumentException("NormCode is required.", nameof(normCode)); if (string.IsNullOrWhiteSpace(unit)) throw new ArgumentException("Unit is required.", nameof(unit)); return $"{workCode.Trim()}|{normCode.Trim()}|{unit.Trim()}"; }
    private static ResolvedQtoDimension ResolveDimension(QtoDimension dimension, IReadOnlyList<QtoDimension> ordered, IReadOnlyDictionary<string, QtoDimension> byId, IDictionary<string, ResolutionState> state, IDictionary<string, ResolvedQtoDimension> resolved, string revisionId) { ValidateDimension(dimension, revisionId); if (resolved.TryGetValue(dimension.DimensionId, out var cached)) return cached; if (state.TryGetValue(dimension.DimensionId, out var current) && current == ResolutionState.Resolving) throw new InvalidOperationException($"Circular QTO reference detected at dimension '{dimension.DimensionId}'."); state[dimension.DimensionId] = ResolutionState.Resolving; try { decimal quantity; string? carryDownSource = null; if (dimension.IsCarryDown) { var source = ordered.Where(x => x.Sequence < dimension.Sequence && string.Equals(x.EffectiveColumnKey, dimension.EffectiveColumnKey, StringComparison.OrdinalIgnoreCase)).OrderByDescending(x => x.Sequence).ThenByDescending(x => x.DimensionId, StringComparer.Ordinal).FirstOrDefault(); if (source is null) throw new InvalidOperationException($"Carry-down dimension '{dimension.DimensionId}' has no preceding source in column '{dimension.EffectiveColumnKey}'."); if (!string.IsNullOrWhiteSpace(dimension.CarryDownSourceDimensionId) && !string.Equals(dimension.CarryDownSourceDimensionId, source.DimensionId, StringComparison.OrdinalIgnoreCase)) throw new InvalidOperationException($"Carry-down provenance for '{dimension.DimensionId}' does not match the immediately preceding source."); var sourceResolved = ResolveDimension(source, ordered, byId, state, resolved, revisionId); quantity = sourceResolved.Quantity; carryDownSource = source.DimensionId; } else { var expression = NormalizeArithmeticExpression(dimension.Expression); var parser = new FormulaParser(expression, name => { if (!byId.TryGetValue(name, out var referenced)) throw new InvalidOperationException($"Unknown dimension reference '{name}'."); return ResolveDimension(referenced, ordered, byId, state, resolved, revisionId).Quantity; }); quantity = parser.Parse(); } if (dimension.IsDeduction) quantity = -Math.Abs(quantity); var result = new ResolvedQtoDimension(dimension, quantity, dimension.Expression, carryDownSource); resolved[dimension.DimensionId] = result; state[dimension.DimensionId] = ResolutionState.Resolved; return result; } catch { state.Remove(dimension.DimensionId); throw; } }
    private static string NormalizeArithmeticExpression(string expression) { var text = expression.Trim(); if (text == "=") throw new InvalidOperationException("A standalone '=' is a carry-down operator and requires worksheet context."); if (text.Length > 0 && text[0] == '=') text = text[1..].TrimStart(); if (text.Length == 0) throw new InvalidOperationException("QTO arithmetic expression is empty."); return text; }
    private static QtoEstimateItem ToEstimateItem(ProjectItem item) => new(item.ProjectItemID, item.WorkCode, item.Description, item.Unit, item.Quantity, item.NormCode, Array.Empty<string>());
    private static string BuildEvidenceHash(QtoWorksheet worksheet, IReadOnlyList<ProjectItem> items, IReadOnlyList<CostLine> costLines) { var canonical = string.Join("\n", new[] { worksheet.WorksheetId, worksheet.RevisionId, worksheet.SourceHash, worksheet.EvidenceHash, string.Join("|", items.Select(x => $"{x.ProjectItemID}:{x.WorkCode}:{x.NormCode}:{x.Unit}:{x.Quantity.ToString(CultureInfo.InvariantCulture)}")), string.Join("|", costLines.Select(x => $"{x.ProjectItemID}:{x.Material.ToString(CultureInfo.InvariantCulture)}:{x.Labor.ToString(CultureInfo.InvariantCulture)}:{x.Machine.ToString(CultureInfo.InvariantCulture)}")) }); return Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(canonical))); }
    private static void ValidateDimension(QtoDimension dimension, string revisionId) { if (string.IsNullOrWhiteSpace(dimension.DimensionId)) throw new InvalidOperationException("QTO dimension requires DimensionId."); if (!string.Equals(dimension.RevisionId, revisionId, StringComparison.Ordinal)) throw new InvalidOperationException($"Dimension {dimension.DimensionId} belongs to revision {dimension.RevisionId}, not worksheet revision {revisionId}."); if (string.IsNullOrWhiteSpace(dimension.WorkCode)) throw new InvalidOperationException($"Dimension {dimension.DimensionId} requires WorkCode."); if (string.IsNullOrWhiteSpace(dimension.NormCode)) throw new InvalidOperationException($"Dimension {dimension.DimensionId} requires NormCode."); if (string.IsNullOrWhiteSpace(dimension.Unit)) throw new InvalidOperationException($"Dimension {dimension.DimensionId} requires Unit."); if (string.IsNullOrWhiteSpace(dimension.Expression)) throw new InvalidOperationException($"Dimension {dimension.DimensionId} requires Expression."); if (dimension.Sequence < 0) throw new InvalidOperationException($"Dimension {dimension.DimensionId} has invalid sequence."); if (!string.IsNullOrWhiteSpace(dimension.CarryDownSourceDimensionId) && !dimension.IsCarryDown) throw new InvalidOperationException($"Dimension {dimension.DimensionId} contains carry-down provenance but its raw expression is not '='."); }
    private enum ResolutionState { Resolving = 1, Resolved = 2 }
    private sealed class FormulaParser { private readonly string _text; private readonly Func<string, decimal> _resolveVariable; private int _position; public FormulaParser(string text, Func<string, decimal> resolveVariable) { _text = text; _resolveVariable = resolveVariable; } public decimal Parse() { var result = ParseExpression(); SkipWhitespace(); if (_position != _text.Length) throw Error("Unexpected token."); return result; } private decimal ParseExpression() { var value = ParseTerm(); while (true) { SkipWhitespace(); if (Match('+')) value += ParseTerm(); else if (Match('-')) value -= ParseTerm(); else return value; } } private decimal ParseTerm() { var value = ParseFactor(); while (true) { SkipWhitespace(); if (Match('*')) value *= ParseFactor(); else if (Match('/')) { var divisor = ParseFactor(); if (divisor == 0m) throw Error("Division by zero."); value /= divisor; } else return value; } } private decimal ParseFactor() { SkipWhitespace(); if (Match('+')) return ParseFactor(); if (Match('-')) return -ParseFactor(); if (Match('(')) { var value = ParseExpression(); Expect(')'); return value; } if (_position < _text.Length && (char.IsDigit(_text[_position]) || _text[_position] == '.')) return ParseNumber(); var identifier = ParseIdentifier(); return _resolveVariable(identifier); } private decimal ParseNumber() { var start = _position; while (_position < _text.Length && (char.IsDigit(_text[_position]) || _text[_position] == '.')) _position++; var token = _text[start.._position]; if (!decimal.TryParse(token, NumberStyles.Number, CultureInfo.InvariantCulture, out var value)) throw Error($"Invalid number '{token}'."); return value; } private string ParseIdentifier() { SkipWhitespace(); var start = _position; while (_position < _text.Length && (char.IsLetterOrDigit(_text[_position]) || _text[_position] == '_' || _text[_position] == '.')) _position++; if (start == _position) throw Error("Expected number or dimension reference."); return _text[start.._position]; } private bool Match(char c) { if (_position < _text.Length && _text[_position] == c) { _position++; return true; } return false; } private void Expect(char c) { if (!Match(c)) throw Error($"Expected '{c}'."); } private void SkipWhitespace() { while (_position < _text.Length && char.IsWhiteSpace(_text[_position])) _position++; } private InvalidOperationException Error(string message) => new($"Invalid QTO expression at position {_position}: {message}"); }
}
