namespace DTBK.Engine;

/// <summary>Evidence-backed ESCON workspace contract used by DTBK parity tests.</summary>
public static class EsconWorkspaceParityCatalog
{
    public sealed record ColumnContract(string Name,string Alias,string? Formula=null,string? Group=null,bool Input=false,bool BlockSum=false,bool Visible=true);
    public sealed record SheetContract(string Name,string Group,string DataType,IReadOnlyList<ColumnContract> Columns,IReadOnlyList<string> ReferencedSheets,IReadOnlyList<string> Actions);
    public static IReadOnlyList<SheetContract> Sheets { get; } = Build();
    private static IReadOnlyList<SheetContract> Build()
    {
        var sheets = new List<SheetContract>
        {
            new("TIÊN LƯỢNG","TIÊN LƯỢNG","CongTac",new[]{new ColumnContract("STT","STT"),new ColumnContract("KHBV","KÝ HIỆU BẢN VẼ"),new ColumnContract("MaCT","MÃ CT"),new ColumnContract("TenCT","TÊN CÔNG TÁC"),new ColumnContract("DonVi","ĐƠN VỊ"),new ColumnContract("SoCK","SỐ CK",Visible:false),new ColumnContract("KTDai","DÀI",Group:"KÍCH THƯỚC",Visible:false),new ColumnContract("KTRong","RỘNG",Group:"KÍCH THƯỚC",Visible:false),new ColumnContract("KTCao","CAO",Group:"KÍCH THƯỚC",Visible:false),new ColumnContract("HSPhu","HỆ SỐ PHỤ",Visible:false),new ColumnContract("KLPhu","KHỐI LƯỢNG PHỤ","PRODUCT([SoCK];[KTDai];[KTRong];[KTCao];[HSPhu])",Visible:false),new ColumnContract("KhoiLuong","KHỐI LƯỢNG"),new ColumnContract("DGVL","VẬT LIỆU","[Value]*[HSDCVL]","ĐƠN GIÁ",true),new ColumnContract("DGVLP","VL PHỤ","[Value]*[HSDCVL]","ĐƠN GIÁ",true),new ColumnContract("DGNC","NHÂN CÔNG","[Value]*[HSDCNC]","ĐƠN GIÁ",true),new ColumnContract("DGCM","CA MÁY","[Value]*[HSDCCM]","ĐƠN GIÁ",true),new ColumnContract("TTDGVL","VẬT LIỆU","[DGVL]*[KhoiLuong]","THÀNH TIỀN",BlockSum:true),new ColumnContract("TTDGVLP","VL PHỤ","[DGVLP]*[KhoiLuong]","THÀNH TIỀN",BlockSum:true,Visible:false),new ColumnContract("TTDGNC","NHÂN CÔNG","[DGNC]*[KhoiLuong]","THÀNH TIỀN",BlockSum:true),new ColumnContract("TTDGCM","CA MÁY","[DGCM]*[KhoiLuong]","THÀNH TIỀN",BlockSum:true),new ColumnContract("HSDCVL","HSVL",Group:"HỆ SỐ ĐIỀU CHỈNH",Input:true),new ColumnContract("HSDCNC","HSNC",Group:"HỆ SỐ ĐIỀU CHỈNH",Input:true),new ColumnContract("HSDCCM","HSCM",Group:"HỆ SỐ ĐIỀU CHỈNH",Input:true),new ColumnContract("TenDonGia","ĐƠN GIÁ"),new ColumnContract("TenDinhMuc","ĐỊNH MỨC")},Array.Empty<string>(),new[]{"Chèn dòng","Xóa dòng","Ẩn/Hiện dòng, cột","Lựa chọn bộ đơn giá","Phương pháp lập dự toán","Dự toán phát sinh"}),
            new("GIÁ VẬT TƯ","GIÁ VẬT TƯ","VatTu",new[]{new ColumnContract("STT","STT"),new ColumnContract("MaVT","MÃ VT"),new ColumnContract("TenVT","TÊN VẬT TƯ"),new ColumnContract("DonVi","ĐƠN VỊ"),new ColumnContract("TyTrong","TỶ TRỌNG",Input:true),new ColumnContract("NguonMua","NGUỒN MUA",Input:true),new ColumnContract("GiaGoc","GIÁ GỐC",Input:true),new ColumnContract("GiaTB","GIÁ TB","[GiaGoc]",Input:true),new ColumnContract("VAT","TỶ LỆ VAT (%)",Input:true),new ColumnContract("HSDC","HS ĐIỀU CHỈNH",Input:true),new ColumnContract("CuocVCCG","CƯỚC VCCG",Visible:false),new ColumnContract("CuocVCTC","CƯỚC VCTC",Visible:false),new ColumnContract("CuocVCDT","CƯỚC VCĐT",Visible:false),new ColumnContract("CPTCBQ","CP TRUNG CHUYỂN",Visible:false),new ColumnContract("CuocBXCG","BỐC XẾP CƠ GIỚI",Visible:false),new ColumnContract("GiaHT","GIÁ HIỆN TRƯỜNG","[GiaTB]*[HSDC]/(1+[VAT])+[CuocVCCG]+[CuocVCTC]+[CuocVCDT]+[CPTCBQ]")},Array.Empty<string>(),Array.Empty<string>()),
            new("CƯỚC VCCG","GIÁ VẬT TƯ","VatLieu",Array.Empty<ColumnContract>(),new[]{"GIÁ VẬT TƯ"},Array.Empty<string>()),new("CƯỚC VCTC","GIÁ VẬT TƯ","VatLieu",Array.Empty<ColumnContract>(),new[]{"CƯỚC VCCG"},Array.Empty<string>()),new("CƯỚC VCDT","GIÁ VẬT TƯ","VatLieu",Array.Empty<ColumnContract>(),new[]{"GIÁ VẬT TƯ"},Array.Empty<string>()),new("CP TRUNG CHUYỂN","GIÁ VẬT TƯ","VatLieu",Array.Empty<ColumnContract>(),new[]{"GIÁ VẬT TƯ"},Array.Empty<string>()),new("GIÁ NHÂN CÔNG","GIÁ NHÂN CÔNG","NhanCong",Array.Empty<ColumnContract>(),Array.Empty<string>(),Array.Empty<string>()),new("NCLM GỐC","NCLM","NhanCong",Array.Empty<ColumnContract>(),new[]{"GIÁ NHÂN CÔNG"},Array.Empty<string>()),new("NCLM HIỆN TẠI","NCLM","NhanCong",Array.Empty<ColumnContract>(),new[]{"NCLM GỐC"},Array.Empty<string>()),new("PT MÁY","MÁY","May",Array.Empty<ColumnContract>(),Array.Empty<string>(),Array.Empty<string>()),new("TH MÁY","MÁY","May",Array.Empty<ColumnContract>(),new[]{"PT MÁY"},Array.Empty<string>()),new("PT BÙ GIÁ MÁY","MÁY","May",Array.Empty<ColumnContract>(),new[]{"PT MÁY"},Array.Empty<string>()),new("TH BÙ GIÁ MÁY","MÁY","May",Array.Empty<ColumnContract>(),new[]{"PT BÙ GIÁ MÁY"},Array.Empty<string>()),new("PT VẬT TƯ","VẬT TƯ","VatTu",Array.Empty<ColumnContract>(),new[]{"GIÁ VẬT TƯ"},Array.Empty<string>()),new("TH VẬT TƯ","VẬT TƯ","VatTu",Array.Empty<ColumnContract>(),new[]{"PT VẬT TƯ"},Array.Empty<string>()),new("NHIÊN LIỆU, NCLM","NHIÊN LIỆU","NhienLieu",Array.Empty<ColumnContract>(),new[]{"NCLM HIỆN TẠI"},Array.Empty<string>()),new("DG CÔNG TRÌNH","ĐƠN GIÁ","CongTrinh",Array.Empty<ColumnContract>(),new[]{"GIÁ VẬT TƯ","GIÁ NHÂN CÔNG","PT MÁY"},Array.Empty<string>()),new("THKPHM","TỔNG HỢP","TongHop",Array.Empty<ColumnContract>(),new[]{"DG CÔNG TRÌNH"},Array.Empty<string>()),new("CP THIẾT BỊ","CHI PHÍ","ChiPhi",Array.Empty<ColumnContract>(),new[]{"THKPHM"},Array.Empty<string>()),new("CP XÂY DỰNG","CHI PHÍ","ChiPhi",Array.Empty<ColumnContract>(),new[]{"DG CÔNG TRÌNH","THKPHM"},Array.Empty<string>()),new("HẠNG MỤC CHUNG","CHI PHÍ","ChiPhi",Array.Empty<ColumnContract>(),new[]{"CP XÂY DỰNG"},Array.Empty<string>()),new("DỰ PHÒNG PHÍ","CHI PHÍ","ChiPhi",Array.Empty<ColumnContract>(),new[]{"CP XÂY DỰNG","HẠNG MỤC CHUNG"},Array.Empty<string>()),new("TH KINH PHÍ","TỔNG HỢP","TongHop",Array.Empty<ColumnContract>(),new[]{"CP XÂY DỰNG","HẠNG MỤC CHUNG","DỰ PHÒNG PHÍ"},Array.Empty<string>()),new("BÌA DỰ TOÁN","TỔNG HỢP","Cover",Array.Empty<ColumnContract>(),new[]{"TH KINH PHÍ"},Array.Empty<string>())
        }; return sheets;
    }
}
