using DTBK.Domain;
using DTBK.Policy;
using DTBK.Coefficient;

namespace DTBK.Engine;

public sealed class ProjectCostEngine
{
    private readonly IRateResolver _rates;
    private readonly ICoefficientProvider? _coefficients;
    public ProjectCostEngine(IRateResolver rates, ICoefficientProvider? coefficients = null) { _rates = rates; _coefficients = coefficients; }
    public ProjectCostSummary Calculate(IEnumerable<CostLine> directLines, WorkType workType, CalculationScenario scenario, LocationType location, DateTime effectiveDate, string vatCategory = "STANDARD", RoundingPolicy? roundingPolicy = null, decimal? locationFactor = null, IEnumerable<string>? extraCoefficientCodes = null, decimal transportAmount = 0m)
    {
        if (transportAmount < 0m) throw new ArgumentOutOfRangeException(nameof(transportAmount)); var lines = directLines as IList<CostLine> ?? directLines.ToList(); decimal material, labor, machine;
        if (lines.Count > 50) { object lockObj = new(); material = labor = machine = 0m; Parallel.ForEach(lines, () => (m: 0m, l: 0m, c: 0m), (line, _, local) => (local.m + line.Material, local.l + line.Labor, local.c + line.Machine), local => { lock (lockObj) { material += local.m; labor += local.l; machine += local.c; } }); } else { material = lines.Sum(x => x.Material); labor = lines.Sum(x => x.Labor); machine = lines.Sum(x => x.Machine); }
        var direct = material + labor + machine + transportAmount; CoefficientSet? coefSet = null; decimal appliedCoef = 1.0m; IReadOnlyList<string> coefDescs = Array.Empty<string>();
        if (_coefficients is not null) { coefSet = _coefficients.Resolve(workType, location, effectiveDate, extraCoefficientCodes); appliedCoef = coefSet.TotalFactor; coefDescs = coefSet.Descriptions; if (appliedCoef != 1.0m) { material *= appliedCoef; labor *= appliedCoef; machine *= appliedCoef; transportAmount *= appliedCoef; direct = material + labor + machine + transportAmount; } } else if (locationFactor is > 0 and not 1m) { appliedCoef = locationFactor.Value; coefDescs = new[] { $"LocationFactor ({appliedCoef:0.####})" }; material *= appliedCoef; labor *= appliedCoef; machine *= appliedCoef; transportAmount *= appliedCoef; direct = material + labor + machine + transportAmount; }
        var oh = _rates.Resolve(RateType.Overhead, workType, scenario, location, direct, effectiveDate); var th = _rates.Resolve(RateType.TemporaryHouse, workType, scenario, location, direct, effectiveDate); var uw = _rates.Resolve(RateType.UnspecifiedWork, workType, scenario, location, direct, effectiveDate); var overhead = R(direct * oh.Rate, roundingPolicy); var temporary = R(direct * th.Rate, roundingPolicy); var unspecified = R(direct * uw.Rate, roundingPolicy); var indirect = overhead + temporary + unspecified; var baseTax = direct + indirect; var ti = _rates.Resolve(RateType.TaxableIncome, workType, scenario, location, baseTax, effectiveDate); var taxable = R(baseTax * ti.Rate, roundingPolicy); var beforeTax = direct + indirect + taxable; var vatRule = _rates.ResolveVat(effectiveDate, vatCategory); var vat = R(beforeTax * vatRule.Rate, roundingPolicy);
        var ruleProvenance = new[] { new CalculationProvenance(vatRule.LegalBasisID.ToString(), "", $"VAT:{vatRule.Category}", vatRule.EffectiveFrom, vatRule.EffectiveTo, vatRule.Category, "taxBase * taxRate", roundingPolicy?.PolicyCode ?? "Engine default", DTBK.Domain.VerificationStatus.NeedsVerification), new CalculationProvenance(oh.LegalBasisID.ToString(), "", oh.RuleCode, oh.EffectiveFrom, oh.EffectiveTo, oh.SpecialCondition, "base * rate", roundingPolicy?.PolicyCode ?? "Engine default", DTBK.Domain.VerificationStatus.NeedsVerification), new CalculationProvenance(th.LegalBasisID.ToString(), "", th.RuleCode, th.EffectiveFrom, th.EffectiveTo, th.SpecialCondition, "base * rate", roundingPolicy?.PolicyCode ?? "Engine default", DTBK.Domain.VerificationStatus.NeedsVerification), new CalculationProvenance(uw.LegalBasisID.ToString(), "", uw.RuleCode, uw.EffectiveFrom, uw.EffectiveTo, uw.SpecialCondition, "base * rate", roundingPolicy?.PolicyCode ?? "Engine default", DTBK.Domain.VerificationStatus.NeedsVerification), new CalculationProvenance(ti.LegalBasisID.ToString(), "", ti.RuleCode, ti.EffectiveFrom, ti.EffectiveTo, ti.SpecialCondition, "base * rate", roundingPolicy?.PolicyCode ?? "Engine default", DTBK.Domain.VerificationStatus.NeedsVerification) };
        return new ProjectCostSummary { DirectMaterial = material, DirectLabor = labor, DirectMachine = machine, DirectTransport = transportAmount, DirectCost = direct, Overhead = overhead, TemporaryHouse = temporary, UnspecifiedWork = unspecified, IndirectCost = indirect, TaxableIncome = taxable, ConstructionCostBeforeTax = beforeTax, VAT = vat, TotalConstructionCost = beforeTax + vat, OverheadRate = oh.Rate, TemporaryHouseRate = th.Rate, UnspecifiedWorkRate = uw.Rate, TaxableIncomeRate = ti.Rate, VATRate = vatRule.Rate, AppliedCoefficient = appliedCoef, AppliedCoefficients = coefDescs, RuleProvenance = ruleProvenance, AppliedScenario = scenario.ToString(), LocationCode = location.ToString(), EngineVersion = "2.7.0" };
    }
    static decimal R(decimal v, RoundingPolicy? p) => p is null ? Math.Round(v, 0, MidpointRounding.AwayFromZero) : RoundingPolicyEngine.RoundCurrency(v, p);
}
